/**
 * Generated by Training Camp
 * JSON Export Module
 *
 * Exports an AgentDefinition to a clean, portable JSON format
 * suitable for sharing, backup, or import into other systems.
 */

import type { AgentDefinition } from '../../types/agent';

export interface JsonExportData {
  name: string;
  version: number;
  description: string;
  systemPrompt: string;
  tools: {
    name: string;
    description: string;
    type: 'builtin' | 'api' | 'function';
    parameters: {
      name: string;
      type: string;
      description: string;
      required: boolean;
    }[];
  }[];
  flow: AgentDefinition['flow'];
  memory: AgentDefinition['memory'];
  parameters: AgentDefinition['parameters'];
}

/**
 * Exports an AgentDefinition to a formatted JSON string.
 *
 * @param agent - The agent definition to export
 * @returns A formatted JSON string representation of the agent
 */
export function exportToJson(agent: AgentDefinition): string {
  const exportData: JsonExportData = {
    name: agent.name,
    version: agent.version,
    description: agent.description,
    systemPrompt: agent.systemPrompt,
    tools: agent.tools.map((t) => ({
      name: t.name,
      description: t.description,
      type: t.type,
      parameters: t.parameters,
    })),
    flow: agent.flow,
    memory: agent.memory,
    parameters: agent.parameters,
  };

  return JSON.stringify(exportData, null, 2);
}
